const translations = {
  uk: { navFinder:"Пошук університетів", navMethod:"Як користуватися", navAbout:"Про проєкт", eyebrow:"Незалежна база для абітурієнтів з України", title:"Шукайте університети,<br /><em>а не випадкові поради.</em>", intro:"FullRide UA допомагає звузити пошук американських університетів із сильною need-based financial aid для іноземних студентів. Кожен запис веде на офіційне джерело.", verifiedRecords:"перевірених записів", updated:"Оновлено 16 вересня 2026", directory:"База університетів", finderTitle:"Почніть із реальних варіантів", finderHint:"Фільтри не замінюють перевірку вимог. Відкрийте офіційну сторінку перед подачею.", searchLabel:"Назва університету", searchPlaceholder:"Пошук за назвою університету", filterGroup:"Фільтри", needBlind:"Need-blind для international", testFlexible:"Є альтернатива SAT/ACT", feeWaiver:"Можливий fee waiver", englishLabel:"Тест англійської", englishAll:"Тест англійської: будь-який", englishRequired:"Тест англійської: може бути потрібен", englishNotRequired:"Тест англійської: зазвичай не потрібен", reset:"Скинути фільтри", results:"Знайдено: {count}", noResults:"За цими фільтрами поки немає збігів.", aid:"Фінансова допомога", tests:"Тести", english:"Англійська", fee:"Application fee", deadline:"Дедлайн", official:"Офіційна сторінка ↗", verified:"перевірено", methodLabel:"Підхід", methodTitle:"Як читати цю базу", step1Title:"Відфільтруйте стартовий список", step1Text:"Почніть із політики фінансової допомоги та доступних для вас форматів тестування.", step2Title:"Відкрийте першоджерело", step2Text:"Умови, дедлайни й документи завжди перевіряйте на сторінці admissions самого університету.", step3Title:"Зберіть збалансований список", step3Text:"Навіть університети з full need є дуже конкурентними. Додавайте також реалістичні варіанти.", aboutLabel:"Про проєкт", aboutTitle:"Чесна інформація —<br />кращий початок.", aboutText:"FullRide UA — не агентство і не гарантія вступу. Це відкритий проєкт, створений, щоб українським учням було простіше знаходити перевірену інформацію про фінансову допомогу в США.", feedback:"Повідомити про неточність <span>↗</span>", footer:"Пілотна версія · Дані потребують регулярної перевірки" },
  ru: { navFinder:"Поиск университетов", navMethod:"Как пользоваться", navAbout:"О проекте", eyebrow:"Независимая база для абитуриентов из Украины", title:"Ищите университеты,<br /><em>а не случайные советы.</em>", intro:"FullRide UA помогает сузить поиск американских университетов с сильной need-based financial aid для иностранных студентов. Каждая запись ведёт к официальному источнику.", verifiedRecords:"проверенных записей", updated:"Обновлено 16 сентября 2026", directory:"База университетов", finderTitle:"Начните с реальных вариантов", finderHint:"Фильтры не заменяют проверку требований. Откройте официальную страницу до подачи заявки.", searchLabel:"Название университета", searchPlaceholder:"Поиск по названию университета", filterGroup:"Фильтры", needBlind:"Need-blind для international", testFlexible:"Есть альтернатива SAT/ACT", feeWaiver:"Возможен fee waiver", englishLabel:"Тест английского", englishAll:"Тест английского: любой", englishRequired:"Тест английского: может требоваться", englishNotRequired:"Тест английского: обычно не нужен", reset:"Сбросить фильтры", results:"Найдено: {count}", noResults:"По этим фильтрам пока нет совпадений.", aid:"Финансовая помощь", tests:"Тесты", english:"Английский", fee:"Application fee", deadline:"Дедлайн", official:"Официальная страница ↗", verified:"проверено", methodLabel:"Подход", methodTitle:"Как читать эту базу", step1Title:"Отфильтруйте стартовый список", step1Text:"Начните с политики финансовой помощи и доступных вам форматов тестирования.", step2Title:"Откройте первоисточник", step2Text:"Условия, дедлайны и документы всегда проверяйте на странице admissions самого университета.", step3Title:"Соберите сбалансированный список", step3Text:"Даже университеты с full need очень конкурентны. Добавляйте также реалистичные варианты.", aboutLabel:"О проекте", aboutTitle:"Честная информация —<br />лучший старт.", aboutText:"FullRide UA — не агентство и не гарантия поступления. Это открытый проект, созданный, чтобы украинским школьникам было проще находить проверенную информацию о финансовой помощи в США.", feedback:"Сообщить о неточности <span>↗</span>", footer:"Пилотная версия · Данные требуют регулярной проверки" },
  en: { navFinder:"College Finder", navMethod:"How to use it", navAbout:"About", eyebrow:"An independent resource for applicants from Ukraine", title:"Find universities,<br /><em>not random advice.</em>", intro:"FullRide UA helps you narrow a U.S. college search around strong need-based financial aid for international students. Every entry links to an official source.", verifiedRecords:"verified records", updated:"Updated September 16, 2026", directory:"University directory", finderTitle:"Start with realistic options", finderHint:"Filters do not replace checking requirements. Open the official page before applying.", searchLabel:"University name", searchPlaceholder:"Search by university name", filterGroup:"Filters", needBlind:"Need-blind for international applicants", testFlexible:"SAT/ACT alternative available", feeWaiver:"Fee waiver available", englishLabel:"English test", englishAll:"English test: any", englishRequired:"English test: may be required", englishNotRequired:"English test: not usually required", reset:"Reset filters", results:"Found: {count}", noResults:"There are no matches for these filters yet.", aid:"Financial aid", tests:"Testing", english:"English", fee:"Application fee", deadline:"Deadline", official:"Official source ↗", verified:"verified", methodLabel:"Method", methodTitle:"How to read this directory", step1Title:"Filter a starting list", step1Text:"Start with aid policy and testing routes that are accessible to you.", step2Title:"Open the primary source", step2Text:"Always confirm requirements, deadlines and documents on the university's own admissions page.", step3Title:"Build a balanced list", step3Text:"Even full-need universities are highly selective. Include realistic options too.", aboutLabel:"About the project", aboutTitle:"Clear information —<br />a better beginning.", aboutText:"FullRide UA is not an agency and does not guarantee admission. It is an open project intended to help Ukrainian students find verified information on U.S. financial aid.", feedback:"Report an inaccuracy <span>↗</span>", footer:"Pilot version · Data should be checked regularly" }
};

let language = "uk";
const q = (id) => document.getElementById(id);
const t = (key) => translations[language][key] || key;

function updateLanguage() {
  document.documentElement.lang = language;
  document.querySelectorAll("[data-i18n]").forEach(el => { el.textContent = t(el.dataset.i18n); });
  document.querySelectorAll("[data-i18n-html]").forEach(el => { el.innerHTML = t(el.dataset.i18nHtml); });
  document.querySelectorAll("[data-i18n-placeholder]").forEach(el => { el.placeholder = t(el.dataset.i18nPlaceholder); });
  document.querySelectorAll("[data-i18n-aria]").forEach(el => { el.setAttribute("aria-label", t(el.dataset.i18nAria)); });
  document.querySelectorAll("[data-lang]").forEach(btn => btn.classList.toggle("active", btn.dataset.lang === language));
  render();
}

function render() {
  const text = q("search").value.trim().toLowerCase();
  const matches = colleges.filter(c => {
    const searchable = `${c.name} ${c.short} ${c.location}`.toLowerCase();
    return (!text || searchable.includes(text)) && (!q("need-blind").checked || c.needBlind) && (!q("test-flexible").checked || c.testFlexible) && (!q("fee-waiver").checked || c.feeWaiver) && (q("english-test").value === "all" || c.englishStatus === q("english-test").value);
  });
  q("results-count").textContent = t("results").replace("{count}", matches.length);
  q("college-count").textContent = colleges.length;
  q("results").innerHTML = matches.length ? matches.map(c => `
    <article class="card">
      <div class="card-top"><div><h3>${c.name}</h3><p class="place">${c.location}</p></div><span class="badge">${c.aidShort}</span></div>
      <dl class="details">
        <div class="detail"><dt>${t("aid")}</dt><dd>${c.aid}</dd></div>
        <div class="detail"><dt>${t("tests")}</dt><dd>${c.testing}</dd></div>
        <div class="detail"><dt>${t("english")}</dt><dd>${c.english}</dd></div>
        <div class="detail"><dt>${t("fee")}</dt><dd>${c.fee}</dd></div>
      </dl>
      <div class="card-footer"><a href="${c.source}" target="_blank" rel="noopener noreferrer">${t("official")}</a><span>${t("verified")}</span></div>
    </article>`).join("") : `<p class="empty">${t("noResults")}</p>`;
}

["search", "need-blind", "test-flexible", "fee-waiver", "english-test"].forEach(id => q(id).addEventListener(id === "search" ? "input" : "change", render));
q("reset").addEventListener("click", () => { q("search").value = ""; q("need-blind").checked = false; q("test-flexible").checked = false; q("fee-waiver").checked = false; q("english-test").value = "all"; render(); });
document.querySelectorAll("[data-lang]").forEach(btn => btn.addEventListener("click", () => { language = btn.dataset.lang; updateLanguage(); }));
updateLanguage();
